### ISSUE TITLE
Issues with VaadinGridSample

### ISSUE THREAD

**Issue by cpboyd** [vaadin/gwt-polymer-elements#143]
Per commit https://github.com/vaadin/gwt-polymer-elements/commit/6d1e8f3038b18d8fb75f8a9196b5219fb0a81be3

An invalid import reference was added:
`import com.vaadin.polymer.demo.client.sampler.Sampler.UseContacts;`

On line 85, variable `e` was never declared: `e.getFirstChild();`

Perhaps `cellElm` was intended here?

**Comment by DecimusMaximus** [comment]
I had the same problem and then saw your issue. I commented out
`import com.vaadin.polymer.demo.client.sampler.Sampler.UseContacts;`

and edited the undeclared _e_ variable to _cellElm_ at your suggestion. It now works.

I also changed <nodeVersion> to v6.9.3, maven-antrun-plugin to 1.8 in the pom.xml file since it gave some error when running mvn clean package.

**Comment by manolo** [comment]
Fixed
