### ISSUE TITLE
Manolo's demo - dialog box gets displayed UNDER the Drawer in iOS

### ISSUE THREAD

**Issue by biancashouse** [vaadin/gwt-polymer-elements#49]
Do we have to explicitly set z-index on a PaperDialog to make it float above the page ?

In the iOS simulator and on an iPad, it is below the drawer.   ;-(
On my Nexus 7 it works correctly ;-)

I ask this, because I imagine the vaadin widget and element are simply facades for Polymer:

```
When we find a bug like this, is it a bug in your Widget or is it likely 
to be an actual bug in the actual polymer web component ?
```

Cheers

Ian

**Comment by manolo** [comment]
what do you mean with manolo's demo, is it the official demo of gwt-polymer-elements.

Many things have changed since you reported this, could you try last demo?

Anyway, normally these visual bugs are related with the original polymer element, and bugs related with setting properties with the vaadin wrapper.

**Comment by biancashouse** [comment]
Hi Manuel,

I must have been smoking a joint when I wrote that email.
Anyway, until web components are supported properly I decided to avoid them.
Why is it that Apple are such a pain in the arse these days ?

Thanks

Ian

**Comment by manolo** [comment]
could you test with last demo? it might be fixed.

**Comment by manolo** [comment]
Fixed
