### ISSUE TITLE
Update showcase

### ISSUE THREAD

**Issue by jouni** [vaadin/gwt-polymer-elements#69]
- Move GWT integration “tab” to last in the sidebar
- Add “Vaadin Grid” tab after Iron elements
  - Start with the "REST API data source" sample
  - Add frozen columns
  - Add column hiding and reordering
  - Sorting

**Comment by manolo** [comment]
@jounik finally I did the long way of making vaadin-grid work with the gwt-api-generator.

In this way the demo code looks simpler since the WC api is less complex than using vaadin-widgets.jar and the demo was easier to write because I reused some material from vaadin-grid examples.

The demo shows more features than the set defined in this card, so we have:
- ajax
- frozen colums
- hiding (no reording)
- sorting
- cell generators
- class generators
- resizing
- filtering using paper-input
- row details

I think it's more logic to use the grid as a web component in the showcase, because the audience expects that.

Live demo is at: http://manolo.github.io/gwt-polymer-elements/demo/#vaadin/VaadinGridSample

**Comment by jouni** [comment]
Oh, wow! That sounds great! I wasn’t expecting this to work so soon.

This is probably pending some patches in vaadin-grid, right?

**Comment by manolo** [comment]
Yes we need:
https://github.com/vaadin/vaadin-grid/pull/239
https://github.com/vaadin/vaadin-elements/pull/21
