### ISSUE TITLE
Remove Google tracking

### ISSUE THREAD

**Issue by christianbauer** [vaadin/gwt-polymer-elements#89]
Google is tracking component users through their font servers, every page load results in requests to https://fonts.googleapis.com/css?family=Roboto+Mono:400,700 etc.

If I use Google components directly, I always remove this to protect my users' privacy. Maybe you can exclude this when converting the components as well.

**Comment by manolo** [comment]
Could you elaborate a bit ? from where do you want us to remove this call ?

**Comment by christianbauer** [comment]
http://vaadin.github.io/gwt-polymer-elements/demo/gwtPolymerDemo/bower_components/font-roboto/roboto.html

**Comment by manolo** [comment]
We must provide the `roboto.html` as part of our `bower_components` bundle in order no to break dependencies. We cannot modify the file because other users could be interested on using it.

The user could avoid using that class just providing an empty `bower_components/font-roboto/roboto.html` in their `public` folder, so as this would override the bundled one.
