### ISSUE TITLE
Vaadin-Grid getItem is wrong defined and not usable

### ISSUE THREAD

**Issue by frankstolle** [vaadin/gwt-polymer-elements#91]
If I want to use grid.getItem(..) I have to define a callback-Method. 

``` java
    public void getItem(double rowIndex, Function callback, boolean onlyCached);
```

The callback of type function allows only one argument, but the grid expects two arguments. Here the type Function seems to be wrong and an individual type should be used. 
As workaround I have written a Wrapper, because extending Function is not possible:

``` java
public abstract class GetItemHelper<R> {

    public abstract void handleCallback(Object error, R item);

    public native Function getCallback() /*-{
        var that=this;
        return function(err, item) {
            that.@GetItemHelper::handleCallback(*)(err, item);
        }
    }-*/;
}
```

The call is then:

``` java
VaadinGrid grid;
...
grid.getItem(0, new GetItemHelper<Object>() { 
@Override
                public void handleCallback(Object err, R item) {

                }
}.getCallback(), true);
```

**Comment by manolo** [comment]
Unfortunatelly, gwt-api-generator does not handle this kind of cases, it is difficult to handle in this project without introducing a hack for this case.

There are two options for you:
- Continue declaring your own workaround, but I'd recommend to use JsInterop instead of JSNI:

```
interface VGrid extends VaadinGridElement {
    @JsFunction
    interface ItemCallback {
        void call(JavaScriptObject error, JavaScriptObject item);
    }
    @JsMethod
    void getItem(double rowIndex, ItemCallback callback, boolean onlyCached);
}

((VGrid) grid.getPolymerElement()).getItem(idx, (err, item) -> { ... }, false);

```
- Open an issue to https://github.com/vaadin/vaadin-grid component to invert the order of the Items callback arguments, so as first one is item.

**Comment by manolo** [comment]
Reopening since gwt-api-generator allows extending base classes with java code.
